### PR TITLE
Add requirements

### PR DESCRIPTION
**Pull request by slaysd**

### CODE REVIEW

**Comment by slaysd** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **jinh574**

If they are not already assigned, you can assign the PR to them by writing `/assign @jinh574` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ids-tekton%2Ftest04).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ids-tekton/test04/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jinh574** [comment]
@jinh574: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | 4348433ac11762e727c88efbbbc1c77342e73adf | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by jinh574** [comment]
@jinh574: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | b81600d56da3bb0d750ef75c89332d4707926749 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by slaysd** [comment]
:star: PR built and available in a preview environment **ids-tekton-test04-pr-1** [here](http://test04.jx-ids-tekton-test04-pr-1.35.200.12.120.nip.io)

**Comment by slaysd** [comment]
:star: PR built and available in a preview environment **ids-tekton-test04-pr-1** [here](http://test04.jx-ids-tekton-test04-pr-1.35.200.12.120.nip.io)

**Pull request closed without merging**
